### YamlMime:ManagedReference
items:
- uid: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig
  commentId: T:Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig
  id: RgbPwmLed.RunningColorsConfig
  parent: Meadow.Foundation.LEDs
  children:
  - Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Colors
  - Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Durations
  - Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Loop
  langs:
  - csharp
  - vb
  name: RgbPwmLed.RunningColorsConfig
  nameWithType: RgbPwmLed.RunningColorsConfig
  fullName: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig
  type: Class
  source:
    remote:
      path: Source/Meadow.Foundation/LEDs/RgbPwmLed.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Foundation.git
    id: RunningColorsConfig
    path: ../Meadow.Foundation/Source/Meadow.Foundation/LEDs/RgbPwmLed.cs
    startLine: 18
  assemblies:
  - Meadow.Foundation
  namespace: Meadow.Foundation.LEDs
  syntax:
    content: 'protected class RunningColorsConfig : object'
    content.vb: >-
      Protected Class RunningColorsConfig
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - protected
  - class
  modifiers.vb:
  - Protected
  - Class
- uid: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Colors
  commentId: P:Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Colors
  id: Colors
  parent: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig
  langs:
  - csharp
  - vb
  name: Colors
  nameWithType: RgbPwmLed.RunningColorsConfig.Colors
  fullName: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Colors
  type: Property
  source:
    remote:
      path: Source/Meadow.Foundation/LEDs/RgbPwmLed.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Foundation.git
    id: Colors
    path: ../Meadow.Foundation/Source/Meadow.Foundation/LEDs/RgbPwmLed.cs
    startLine: 20
  assemblies:
  - Meadow.Foundation
  namespace: Meadow.Foundation.LEDs
  syntax:
    content: public ArrayList Colors { get; set; }
    parameters: []
    return:
      type: ArrayList
    content.vb: Public Property Colors As ArrayList
  overload: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Colors*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Durations
  commentId: P:Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Durations
  id: Durations
  parent: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig
  langs:
  - csharp
  - vb
  name: Durations
  nameWithType: RgbPwmLed.RunningColorsConfig.Durations
  fullName: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Durations
  type: Property
  source:
    remote:
      path: Source/Meadow.Foundation/LEDs/RgbPwmLed.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Foundation.git
    id: Durations
    path: ../Meadow.Foundation/Source/Meadow.Foundation/LEDs/RgbPwmLed.cs
    startLine: 21
  assemblies:
  - Meadow.Foundation
  namespace: Meadow.Foundation.LEDs
  syntax:
    content: public int[] Durations { get; set; }
    parameters: []
    return:
      type: System.Int32[]
    content.vb: Public Property Durations As Integer()
  overload: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Durations*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Loop
  commentId: P:Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Loop
  id: Loop
  parent: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig
  langs:
  - csharp
  - vb
  name: Loop
  nameWithType: RgbPwmLed.RunningColorsConfig.Loop
  fullName: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Loop
  type: Property
  source:
    remote:
      path: Source/Meadow.Foundation/LEDs/RgbPwmLed.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Foundation.git
    id: Loop
    path: ../Meadow.Foundation/Source/Meadow.Foundation/LEDs/RgbPwmLed.cs
    startLine: 22
  assemblies:
  - Meadow.Foundation
  namespace: Meadow.Foundation.LEDs
  syntax:
    content: public bool Loop { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Loop As Boolean
  overload: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Loop*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Meadow.Foundation.LEDs
  commentId: N:Meadow.Foundation.LEDs
  name: Meadow.Foundation.LEDs
  nameWithType: Meadow.Foundation.LEDs
  fullName: Meadow.Foundation.LEDs
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Colors*
  commentId: Overload:Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Colors
  name: Colors
  nameWithType: RgbPwmLed.RunningColorsConfig.Colors
  fullName: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Colors
- uid: ArrayList
  isExternal: true
  name: ArrayList
  nameWithType: ArrayList
  fullName: ArrayList
- uid: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Durations*
  commentId: Overload:Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Durations
  name: Durations
  nameWithType: RgbPwmLed.RunningColorsConfig.Durations
  fullName: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Durations
- uid: System.Int32[]
  isExternal: true
  name: Int32[]
  nameWithType: Int32[]
  fullName: System.Int32[]
  nameWithType.vb: Int32()
  fullName.vb: System.Int32()
  name.vb: Int32()
  spec.csharp:
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: ()
    nameWithType: ()
    fullName: ()
- uid: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Loop*
  commentId: Overload:Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Loop
  name: Loop
  nameWithType: RgbPwmLed.RunningColorsConfig.Loop
  fullName: Meadow.Foundation.LEDs.RgbPwmLed.RunningColorsConfig.Loop
- uid: System.Boolean
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
