### YamlMime:ManagedReference
items:
- uid: Meadow.Foundation.Servos.ServoConfig
  commentId: T:Meadow.Foundation.Servos.ServoConfig
  id: ServoConfig
  parent: Meadow.Foundation.Servos
  children:
  - Meadow.Foundation.Servos.ServoConfig.#ctor(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32)
  - Meadow.Foundation.Servos.ServoConfig.Frequency
  - Meadow.Foundation.Servos.ServoConfig.MaximumAngle
  - Meadow.Foundation.Servos.ServoConfig.MaximumPulseDuration
  - Meadow.Foundation.Servos.ServoConfig.MinimumAngle
  - Meadow.Foundation.Servos.ServoConfig.MinimumPulseDuration
  langs:
  - csharp
  - vb
  name: ServoConfig
  nameWithType: ServoConfig
  fullName: Meadow.Foundation.Servos.ServoConfig
  type: Class
  source:
    remote:
      path: Source/Peripheral_Libs/Sensors.Servo.Core/ServoConfig.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Foundation.git
    id: ServoConfig
    path: ../Meadow.Foundation/Source/Peripheral_Libs/Sensors.Servo.Core/ServoConfig.cs
    startLine: 4
  assemblies:
  - Sensors.Servo.Core
  namespace: Meadow.Foundation.Servos
  syntax:
    content: 'public class ServoConfig : object'
    content.vb: >-
      Public Class ServoConfig

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Meadow.Foundation.Servos.ServoConfig.MinimumAngle
  commentId: P:Meadow.Foundation.Servos.ServoConfig.MinimumAngle
  id: MinimumAngle
  parent: Meadow.Foundation.Servos.ServoConfig
  langs:
  - csharp
  - vb
  name: MinimumAngle
  nameWithType: ServoConfig.MinimumAngle
  fullName: Meadow.Foundation.Servos.ServoConfig.MinimumAngle
  type: Property
  source:
    remote:
      path: Source/Peripheral_Libs/Sensors.Servo.Core/ServoConfig.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Foundation.git
    id: MinimumAngle
    path: ../Meadow.Foundation/Source/Peripheral_Libs/Sensors.Servo.Core/ServoConfig.cs
    startLine: 6
  assemblies:
  - Sensors.Servo.Core
  namespace: Meadow.Foundation.Servos
  syntax:
    content: public int MinimumAngle { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public ReadOnly Property MinimumAngle As Integer
  overload: Meadow.Foundation.Servos.ServoConfig.MinimumAngle*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Meadow.Foundation.Servos.ServoConfig.MaximumAngle
  commentId: P:Meadow.Foundation.Servos.ServoConfig.MaximumAngle
  id: MaximumAngle
  parent: Meadow.Foundation.Servos.ServoConfig
  langs:
  - csharp
  - vb
  name: MaximumAngle
  nameWithType: ServoConfig.MaximumAngle
  fullName: Meadow.Foundation.Servos.ServoConfig.MaximumAngle
  type: Property
  source:
    remote:
      path: Source/Peripheral_Libs/Sensors.Servo.Core/ServoConfig.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Foundation.git
    id: MaximumAngle
    path: ../Meadow.Foundation/Source/Peripheral_Libs/Sensors.Servo.Core/ServoConfig.cs
    startLine: 7
  assemblies:
  - Sensors.Servo.Core
  namespace: Meadow.Foundation.Servos
  syntax:
    content: public int MaximumAngle { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public ReadOnly Property MaximumAngle As Integer
  overload: Meadow.Foundation.Servos.ServoConfig.MaximumAngle*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Meadow.Foundation.Servos.ServoConfig.MinimumPulseDuration
  commentId: P:Meadow.Foundation.Servos.ServoConfig.MinimumPulseDuration
  id: MinimumPulseDuration
  parent: Meadow.Foundation.Servos.ServoConfig
  langs:
  - csharp
  - vb
  name: MinimumPulseDuration
  nameWithType: ServoConfig.MinimumPulseDuration
  fullName: Meadow.Foundation.Servos.ServoConfig.MinimumPulseDuration
  type: Property
  source:
    remote:
      path: Source/Peripheral_Libs/Sensors.Servo.Core/ServoConfig.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Foundation.git
    id: MinimumPulseDuration
    path: ../Meadow.Foundation/Source/Peripheral_Libs/Sensors.Servo.Core/ServoConfig.cs
    startLine: 8
  assemblies:
  - Sensors.Servo.Core
  namespace: Meadow.Foundation.Servos
  syntax:
    content: public int MinimumPulseDuration { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public ReadOnly Property MinimumPulseDuration As Integer
  overload: Meadow.Foundation.Servos.ServoConfig.MinimumPulseDuration*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Meadow.Foundation.Servos.ServoConfig.MaximumPulseDuration
  commentId: P:Meadow.Foundation.Servos.ServoConfig.MaximumPulseDuration
  id: MaximumPulseDuration
  parent: Meadow.Foundation.Servos.ServoConfig
  langs:
  - csharp
  - vb
  name: MaximumPulseDuration
  nameWithType: ServoConfig.MaximumPulseDuration
  fullName: Meadow.Foundation.Servos.ServoConfig.MaximumPulseDuration
  type: Property
  source:
    remote:
      path: Source/Peripheral_Libs/Sensors.Servo.Core/ServoConfig.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Foundation.git
    id: MaximumPulseDuration
    path: ../Meadow.Foundation/Source/Peripheral_Libs/Sensors.Servo.Core/ServoConfig.cs
    startLine: 9
  assemblies:
  - Sensors.Servo.Core
  namespace: Meadow.Foundation.Servos
  syntax:
    content: public int MaximumPulseDuration { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public ReadOnly Property MaximumPulseDuration As Integer
  overload: Meadow.Foundation.Servos.ServoConfig.MaximumPulseDuration*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Meadow.Foundation.Servos.ServoConfig.Frequency
  commentId: P:Meadow.Foundation.Servos.ServoConfig.Frequency
  id: Frequency
  parent: Meadow.Foundation.Servos.ServoConfig
  langs:
  - csharp
  - vb
  name: Frequency
  nameWithType: ServoConfig.Frequency
  fullName: Meadow.Foundation.Servos.ServoConfig.Frequency
  type: Property
  source:
    remote:
      path: Source/Peripheral_Libs/Sensors.Servo.Core/ServoConfig.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Foundation.git
    id: Frequency
    path: ../Meadow.Foundation/Source/Peripheral_Libs/Sensors.Servo.Core/ServoConfig.cs
    startLine: 11
  assemblies:
  - Sensors.Servo.Core
  namespace: Meadow.Foundation.Servos
  syntax:
    content: public int Frequency { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public ReadOnly Property Frequency As Integer
  overload: Meadow.Foundation.Servos.ServoConfig.Frequency*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Meadow.Foundation.Servos.ServoConfig.#ctor(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32)
  commentId: M:Meadow.Foundation.Servos.ServoConfig.#ctor(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32)
  id: '#ctor(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32)'
  parent: Meadow.Foundation.Servos.ServoConfig
  langs:
  - csharp
  - vb
  name: ServoConfig(Int32, Int32, Int32, Int32, Int32)
  nameWithType: ServoConfig.ServoConfig(Int32, Int32, Int32, Int32, Int32)
  fullName: Meadow.Foundation.Servos.ServoConfig.ServoConfig(System.Int32, System.Int32, System.Int32, System.Int32, System.Int32)
  type: Constructor
  source:
    remote:
      path: Source/Peripheral_Libs/Sensors.Servo.Core/ServoConfig.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Foundation.git
    id: .ctor
    path: ../Meadow.Foundation/Source/Peripheral_Libs/Sensors.Servo.Core/ServoConfig.cs
    startLine: 21
  assemblies:
  - Sensors.Servo.Core
  namespace: Meadow.Foundation.Servos
  summary: "\n\n"
  example: []
  syntax:
    content: public ServoConfig(int minimumAngle = 0, int maximumAngle = 180, int minimumPulseDuration = 1000, int maximumPulseDuration = 2000, int frequency = 50)
    parameters:
    - id: minimumAngle
      type: System.Int32
      description: ''
    - id: maximumAngle
      type: System.Int32
      description: ''
    - id: minimumPulseDuration
      type: System.Int32
      description: The minimum angle&apos;s pulse duration (in microseconds). Default is 1,000 (1.0 millisecond).
    - id: maximumPulseDuration
      type: System.Int32
      description: The maximum angle&apos;s pulse duratino (in microseconds). Default is 2,000 (2.0 milleseconds).
    - id: frequency
      type: System.Int32
      description: ''
    content.vb: Public Sub New(minimumAngle As Integer = 0, maximumAngle As Integer = 180, minimumPulseDuration As Integer = 1000, maximumPulseDuration As Integer = 2000, frequency As Integer = 50)
  overload: Meadow.Foundation.Servos.ServoConfig.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Meadow.Foundation.Servos
  commentId: N:Meadow.Foundation.Servos
  name: Meadow.Foundation.Servos
  nameWithType: Meadow.Foundation.Servos
  fullName: Meadow.Foundation.Servos
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Meadow.Foundation.Servos.ServoConfig.MinimumAngle*
  commentId: Overload:Meadow.Foundation.Servos.ServoConfig.MinimumAngle
  name: MinimumAngle
  nameWithType: ServoConfig.MinimumAngle
  fullName: Meadow.Foundation.Servos.ServoConfig.MinimumAngle
- uid: System.Int32
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Meadow.Foundation.Servos.ServoConfig.MaximumAngle*
  commentId: Overload:Meadow.Foundation.Servos.ServoConfig.MaximumAngle
  name: MaximumAngle
  nameWithType: ServoConfig.MaximumAngle
  fullName: Meadow.Foundation.Servos.ServoConfig.MaximumAngle
- uid: Meadow.Foundation.Servos.ServoConfig.MinimumPulseDuration*
  commentId: Overload:Meadow.Foundation.Servos.ServoConfig.MinimumPulseDuration
  name: MinimumPulseDuration
  nameWithType: ServoConfig.MinimumPulseDuration
  fullName: Meadow.Foundation.Servos.ServoConfig.MinimumPulseDuration
- uid: Meadow.Foundation.Servos.ServoConfig.MaximumPulseDuration*
  commentId: Overload:Meadow.Foundation.Servos.ServoConfig.MaximumPulseDuration
  name: MaximumPulseDuration
  nameWithType: ServoConfig.MaximumPulseDuration
  fullName: Meadow.Foundation.Servos.ServoConfig.MaximumPulseDuration
- uid: Meadow.Foundation.Servos.ServoConfig.Frequency*
  commentId: Overload:Meadow.Foundation.Servos.ServoConfig.Frequency
  name: Frequency
  nameWithType: ServoConfig.Frequency
  fullName: Meadow.Foundation.Servos.ServoConfig.Frequency
- uid: Meadow.Foundation.Servos.ServoConfig.#ctor*
  commentId: Overload:Meadow.Foundation.Servos.ServoConfig.#ctor
  name: ServoConfig
  nameWithType: ServoConfig.ServoConfig
  fullName: Meadow.Foundation.Servos.ServoConfig.ServoConfig
