### YamlMime:ManagedReference
items:
- uid: Meadow.Foundation.Displays.TextDisplayConfig
  commentId: T:Meadow.Foundation.Displays.TextDisplayConfig
  id: TextDisplayConfig
  parent: Meadow.Foundation.Displays
  children:
  - Meadow.Foundation.Displays.TextDisplayConfig.Height
  - Meadow.Foundation.Displays.TextDisplayConfig.Width
  langs:
  - csharp
  - vb
  name: TextDisplayConfig
  nameWithType: TextDisplayConfig
  fullName: Meadow.Foundation.Displays.TextDisplayConfig
  type: Class
  source:
    remote:
      path: Source/Meadow.Foundation/Displays/TextDisplayConfig.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Foundation.git
    id: TextDisplayConfig
    path: ../Meadow.Foundation/Source/Meadow.Foundation/Displays/TextDisplayConfig.cs
    startLine: 4
  assemblies:
  - Meadow.Foundation
  namespace: Meadow.Foundation.Displays
  syntax:
    content: 'public class TextDisplayConfig : object'
    content.vb: >-
      Public Class TextDisplayConfig
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Meadow.Foundation.Displays.TextDisplayConfig.Height
  commentId: F:Meadow.Foundation.Displays.TextDisplayConfig.Height
  id: Height
  parent: Meadow.Foundation.Displays.TextDisplayConfig
  langs:
  - csharp
  - vb
  name: Height
  nameWithType: TextDisplayConfig.Height
  fullName: Meadow.Foundation.Displays.TextDisplayConfig.Height
  type: Field
  source:
    remote:
      path: Source/Meadow.Foundation/Displays/TextDisplayConfig.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Foundation.git
    id: Height
    path: ../Meadow.Foundation/Source/Meadow.Foundation/Displays/TextDisplayConfig.cs
    startLine: 9
  assemblies:
  - Meadow.Foundation
  namespace: Meadow.Foundation.Displays
  summary: "\nHeight of the display in lines (usually 2 or 4).\n"
  example: []
  syntax:
    content: public ushort Height
    return:
      type: System.UInt16
    content.vb: Public Height As UShort
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Meadow.Foundation.Displays.TextDisplayConfig.Width
  commentId: F:Meadow.Foundation.Displays.TextDisplayConfig.Width
  id: Width
  parent: Meadow.Foundation.Displays.TextDisplayConfig
  langs:
  - csharp
  - vb
  name: Width
  nameWithType: TextDisplayConfig.Width
  fullName: Meadow.Foundation.Displays.TextDisplayConfig.Width
  type: Field
  source:
    remote:
      path: Source/Meadow.Foundation/Displays/TextDisplayConfig.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Foundation.git
    id: Width
    path: ../Meadow.Foundation/Source/Meadow.Foundation/Displays/TextDisplayConfig.cs
    startLine: 14
  assemblies:
  - Meadow.Foundation
  namespace: Meadow.Foundation.Displays
  summary: "\nwidth of the display in columns (normally 16 or 20).\n"
  example: []
  syntax:
    content: public ushort Width
    return:
      type: System.UInt16
    content.vb: Public Width As UShort
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Meadow.Foundation.Displays
  commentId: N:Meadow.Foundation.Displays
  name: Meadow.Foundation.Displays
  nameWithType: Meadow.Foundation.Displays
  fullName: Meadow.Foundation.Displays
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.UInt16
  isExternal: true
  name: UInt16
  nameWithType: UInt16
  fullName: System.UInt16
