### YamlMime:ManagedReference
items:
- uid: MeadowApplication
  commentId: N:MeadowApplication
  id: MeadowApplication
  children:
  - MeadowApplication.MyApp
  - MeadowApplication.SomeOtherClass
  langs:
  - csharp
  - vb
  name: MeadowApplication
  nameWithType: MeadowApplication
  fullName: MeadowApplication
  type: Namespace
  assemblies:
  - MeadowApplication
references:
- uid: MeadowApplication.MyApp
  commentId: T:MeadowApplication.MyApp
  name: MyApp
  nameWithType: MyApp
  fullName: MeadowApplication.MyApp
- uid: MeadowApplication.SomeOtherClass
  commentId: T:MeadowApplication.SomeOtherClass
  name: SomeOtherClass
  nameWithType: SomeOtherClass
  fullName: MeadowApplication.SomeOtherClass
