### YamlMime:ManagedReference
items:
- uid: Meadow.Gateway.WiFi.NetworkSecuritySettings
  commentId: T:Meadow.Gateway.WiFi.NetworkSecuritySettings
  id: NetworkSecuritySettings
  parent: Meadow.Gateway.WiFi
  children:
  - Meadow.Gateway.WiFi.NetworkSecuritySettings.#ctor(Meadow.Gateway.WiFi.NetworkAuthenticationType,Meadow.Gateway.WiFi.NetworkEncryptionType)
  - Meadow.Gateway.WiFi.NetworkSecuritySettings.AuthenticationType
  - Meadow.Gateway.WiFi.NetworkSecuritySettings.EncryptionType
  langs:
  - csharp
  - vb
  name: NetworkSecuritySettings
  nameWithType: NetworkSecuritySettings
  fullName: Meadow.Gateway.WiFi.NetworkSecuritySettings
  type: Class
  source:
    remote:
      path: source/Meadow.Core/Gateways/WiFi/NetworkSecuritySettings.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: NetworkSecuritySettings
    path: ../Meadow.Core/source/Meadow.Core/Gateways/WiFi/NetworkSecuritySettings.cs
    startLine: 6
  assemblies:
  - Meadow.Core
  namespace: Meadow.Gateway.WiFi
  summary: "\nRepresents the security setting information of a WiFi network.\n"
  example: []
  syntax:
    content: public class NetworkSecuritySettings
    content.vb: Public Class NetworkSecuritySettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Meadow.Gateway.WiFi.NetworkSecuritySettings.AuthenticationType
  commentId: P:Meadow.Gateway.WiFi.NetworkSecuritySettings.AuthenticationType
  id: AuthenticationType
  parent: Meadow.Gateway.WiFi.NetworkSecuritySettings
  langs:
  - csharp
  - vb
  name: AuthenticationType
  nameWithType: NetworkSecuritySettings.AuthenticationType
  fullName: Meadow.Gateway.WiFi.NetworkSecuritySettings.AuthenticationType
  type: Property
  source:
    remote:
      path: source/Meadow.Core/Gateways/WiFi/NetworkSecuritySettings.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: AuthenticationType
    path: ../Meadow.Core/source/Meadow.Core/Gateways/WiFi/NetworkSecuritySettings.cs
    startLine: 8
  assemblies:
  - Meadow.Core
  namespace: Meadow.Gateway.WiFi
  syntax:
    content: public NetworkAuthenticationType AuthenticationType { get; protected set; }
    parameters: []
    return:
      type: Meadow.Gateway.WiFi.NetworkAuthenticationType
    content.vb: Public Property AuthenticationType As NetworkAuthenticationType
  overload: Meadow.Gateway.WiFi.NetworkSecuritySettings.AuthenticationType*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Meadow.Gateway.WiFi.NetworkSecuritySettings.EncryptionType
  commentId: P:Meadow.Gateway.WiFi.NetworkSecuritySettings.EncryptionType
  id: EncryptionType
  parent: Meadow.Gateway.WiFi.NetworkSecuritySettings
  langs:
  - csharp
  - vb
  name: EncryptionType
  nameWithType: NetworkSecuritySettings.EncryptionType
  fullName: Meadow.Gateway.WiFi.NetworkSecuritySettings.EncryptionType
  type: Property
  source:
    remote:
      path: source/Meadow.Core/Gateways/WiFi/NetworkSecuritySettings.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: EncryptionType
    path: ../Meadow.Core/source/Meadow.Core/Gateways/WiFi/NetworkSecuritySettings.cs
    startLine: 9
  assemblies:
  - Meadow.Core
  namespace: Meadow.Gateway.WiFi
  syntax:
    content: public NetworkEncryptionType EncryptionType { get; protected set; }
    parameters: []
    return:
      type: Meadow.Gateway.WiFi.NetworkEncryptionType
    content.vb: Public Property EncryptionType As NetworkEncryptionType
  overload: Meadow.Gateway.WiFi.NetworkSecuritySettings.EncryptionType*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Meadow.Gateway.WiFi.NetworkSecuritySettings.#ctor(Meadow.Gateway.WiFi.NetworkAuthenticationType,Meadow.Gateway.WiFi.NetworkEncryptionType)
  commentId: M:Meadow.Gateway.WiFi.NetworkSecuritySettings.#ctor(Meadow.Gateway.WiFi.NetworkAuthenticationType,Meadow.Gateway.WiFi.NetworkEncryptionType)
  id: '#ctor(Meadow.Gateway.WiFi.NetworkAuthenticationType,Meadow.Gateway.WiFi.NetworkEncryptionType)'
  parent: Meadow.Gateway.WiFi.NetworkSecuritySettings
  langs:
  - csharp
  - vb
  name: NetworkSecuritySettings(NetworkAuthenticationType, NetworkEncryptionType)
  nameWithType: NetworkSecuritySettings.NetworkSecuritySettings(NetworkAuthenticationType, NetworkEncryptionType)
  fullName: Meadow.Gateway.WiFi.NetworkSecuritySettings.NetworkSecuritySettings(Meadow.Gateway.WiFi.NetworkAuthenticationType, Meadow.Gateway.WiFi.NetworkEncryptionType)
  type: Constructor
  source:
    remote:
      path: source/Meadow.Core/Gateways/WiFi/NetworkSecuritySettings.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: .ctor
    path: ../Meadow.Core/source/Meadow.Core/Gateways/WiFi/NetworkSecuritySettings.cs
    startLine: 11
  assemblies:
  - Meadow.Core
  namespace: Meadow.Gateway.WiFi
  syntax:
    content: public NetworkSecuritySettings(NetworkAuthenticationType authType, NetworkEncryptionType encryptionType)
    parameters:
    - id: authType
      type: Meadow.Gateway.WiFi.NetworkAuthenticationType
    - id: encryptionType
      type: Meadow.Gateway.WiFi.NetworkEncryptionType
    content.vb: Public Sub New(authType As NetworkAuthenticationType, encryptionType As NetworkEncryptionType)
  overload: Meadow.Gateway.WiFi.NetworkSecuritySettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Meadow.Gateway.WiFi
  commentId: N:Meadow.Gateway.WiFi
  name: Meadow.Gateway.WiFi
  nameWithType: Meadow.Gateway.WiFi
  fullName: Meadow.Gateway.WiFi
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Meadow.Gateway.WiFi.NetworkSecuritySettings.AuthenticationType*
  commentId: Overload:Meadow.Gateway.WiFi.NetworkSecuritySettings.AuthenticationType
  name: AuthenticationType
  nameWithType: NetworkSecuritySettings.AuthenticationType
  fullName: Meadow.Gateway.WiFi.NetworkSecuritySettings.AuthenticationType
- uid: Meadow.Gateway.WiFi.NetworkAuthenticationType
  commentId: T:Meadow.Gateway.WiFi.NetworkAuthenticationType
  parent: Meadow.Gateway.WiFi
  name: NetworkAuthenticationType
  nameWithType: NetworkAuthenticationType
  fullName: Meadow.Gateway.WiFi.NetworkAuthenticationType
- uid: Meadow.Gateway.WiFi.NetworkSecuritySettings.EncryptionType*
  commentId: Overload:Meadow.Gateway.WiFi.NetworkSecuritySettings.EncryptionType
  name: EncryptionType
  nameWithType: NetworkSecuritySettings.EncryptionType
  fullName: Meadow.Gateway.WiFi.NetworkSecuritySettings.EncryptionType
- uid: Meadow.Gateway.WiFi.NetworkEncryptionType
  commentId: T:Meadow.Gateway.WiFi.NetworkEncryptionType
  parent: Meadow.Gateway.WiFi
  name: NetworkEncryptionType
  nameWithType: NetworkEncryptionType
  fullName: Meadow.Gateway.WiFi.NetworkEncryptionType
- uid: Meadow.Gateway.WiFi.NetworkSecuritySettings.#ctor*
  commentId: Overload:Meadow.Gateway.WiFi.NetworkSecuritySettings.#ctor
  name: NetworkSecuritySettings
  nameWithType: NetworkSecuritySettings.NetworkSecuritySettings
  fullName: Meadow.Gateway.WiFi.NetworkSecuritySettings.NetworkSecuritySettings
