### YamlMime:ManagedReference
items:
- uid: MeadowApplication.SomeOtherClass
  commentId: T:MeadowApplication.SomeOtherClass
  id: SomeOtherClass
  parent: MeadowApplication
  children:
  - MeadowApplication.SomeOtherClass.#ctor
  langs:
  - csharp
  - vb
  name: SomeOtherClass
  nameWithType: SomeOtherClass
  fullName: MeadowApplication.SomeOtherClass
  type: Class
  source:
    remote:
      path: source/Tests/MeadowApplication/SomeOtherClass.cs
      branch: master
      repo: git@github.com:WildernessLabs/Meadow.Core.git
    id: SomeOtherClass
    path: ../Meadow.Core/source/Tests/MeadowApplication/SomeOtherClass.cs
    startLine: 3
  assemblies:
  - MeadowApplication
  namespace: MeadowApplication
  syntax:
    content: 'public class SomeOtherClass : object'
    content.vb: >-
      Public Class SomeOtherClass

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: MeadowApplication.SomeOtherClass.#ctor
  commentId: M:MeadowApplication.SomeOtherClass.#ctor
  id: '#ctor'
  parent: MeadowApplication.SomeOtherClass
  langs:
  - csharp
  - vb
  name: SomeOtherClass()
  nameWithType: SomeOtherClass.SomeOtherClass()
  fullName: MeadowApplication.SomeOtherClass.SomeOtherClass()
  type: Constructor
  source:
    remote:
      path: source/Tests/MeadowApplication/SomeOtherClass.cs
      branch: master
      repo: git@github.com:WildernessLabs/Meadow.Core.git
    id: .ctor
    path: ../Meadow.Core/source/Tests/MeadowApplication/SomeOtherClass.cs
    startLine: 5
  assemblies:
  - MeadowApplication
  namespace: MeadowApplication
  syntax:
    content: public SomeOtherClass()
    content.vb: Public Sub New
  overload: MeadowApplication.SomeOtherClass.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: MeadowApplication
  commentId: N:MeadowApplication
  name: MeadowApplication
  nameWithType: MeadowApplication
  fullName: MeadowApplication
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: MeadowApplication.SomeOtherClass.#ctor*
  commentId: Overload:MeadowApplication.SomeOtherClass.#ctor
  name: SomeOtherClass
  nameWithType: SomeOtherClass.SomeOtherClass
  fullName: MeadowApplication.SomeOtherClass.SomeOtherClass
