### YamlMime:ManagedReference
items:
- uid: Meadow.Hardware.ChannelConfigurationType
  commentId: T:Meadow.Hardware.ChannelConfigurationType
  id: ChannelConfigurationType
  parent: Meadow.Hardware
  children:
  - Meadow.Hardware.ChannelConfigurationType.AnalogInput
  - Meadow.Hardware.ChannelConfigurationType.AnalogOutput
  - Meadow.Hardware.ChannelConfigurationType.CAN
  - Meadow.Hardware.ChannelConfigurationType.DigitalInput
  - Meadow.Hardware.ChannelConfigurationType.DigitalOutput
  - Meadow.Hardware.ChannelConfigurationType.I2C
  - Meadow.Hardware.ChannelConfigurationType.None
  - Meadow.Hardware.ChannelConfigurationType.PWM
  - Meadow.Hardware.ChannelConfigurationType.SPI
  - Meadow.Hardware.ChannelConfigurationType.UART
  langs:
  - csharp
  - vb
  name: ChannelConfigurationType
  nameWithType: ChannelConfigurationType
  fullName: Meadow.Hardware.ChannelConfigurationType
  type: Enum
  source:
    remote:
      path: source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: ChannelConfigurationType
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
    startLine: 89
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  summary: "\nTODO: revisit this structure. Ultimately, it would be nice to know, specifically\nwhat a channel is cofigured for, i.e. DigitalInput, I2C TX, UART RX, etc.\n"
  example: []
  syntax:
    content: public enum ChannelConfigurationType
    content.vb: Public Enum ChannelConfigurationType
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Meadow.Hardware.ChannelConfigurationType.None
  commentId: F:Meadow.Hardware.ChannelConfigurationType.None
  id: None
  parent: Meadow.Hardware.ChannelConfigurationType
  langs:
  - csharp
  - vb
  name: None
  nameWithType: ChannelConfigurationType.None
  fullName: Meadow.Hardware.ChannelConfigurationType.None
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: None
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
    startLine: 91
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: None = 0
    return:
      type: Meadow.Hardware.ChannelConfigurationType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Meadow.Hardware.ChannelConfigurationType.DigitalOutput
  commentId: F:Meadow.Hardware.ChannelConfigurationType.DigitalOutput
  id: DigitalOutput
  parent: Meadow.Hardware.ChannelConfigurationType
  langs:
  - csharp
  - vb
  name: DigitalOutput
  nameWithType: ChannelConfigurationType.DigitalOutput
  fullName: Meadow.Hardware.ChannelConfigurationType.DigitalOutput
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: DigitalOutput
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
    startLine: 92
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: DigitalOutput = 1
    return:
      type: Meadow.Hardware.ChannelConfigurationType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Meadow.Hardware.ChannelConfigurationType.DigitalInput
  commentId: F:Meadow.Hardware.ChannelConfigurationType.DigitalInput
  id: DigitalInput
  parent: Meadow.Hardware.ChannelConfigurationType
  langs:
  - csharp
  - vb
  name: DigitalInput
  nameWithType: ChannelConfigurationType.DigitalInput
  fullName: Meadow.Hardware.ChannelConfigurationType.DigitalInput
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: DigitalInput
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
    startLine: 93
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: DigitalInput = 2
    return:
      type: Meadow.Hardware.ChannelConfigurationType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Meadow.Hardware.ChannelConfigurationType.AnalogOutput
  commentId: F:Meadow.Hardware.ChannelConfigurationType.AnalogOutput
  id: AnalogOutput
  parent: Meadow.Hardware.ChannelConfigurationType
  langs:
  - csharp
  - vb
  name: AnalogOutput
  nameWithType: ChannelConfigurationType.AnalogOutput
  fullName: Meadow.Hardware.ChannelConfigurationType.AnalogOutput
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: AnalogOutput
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
    startLine: 94
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: AnalogOutput = 3
    return:
      type: Meadow.Hardware.ChannelConfigurationType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Meadow.Hardware.ChannelConfigurationType.AnalogInput
  commentId: F:Meadow.Hardware.ChannelConfigurationType.AnalogInput
  id: AnalogInput
  parent: Meadow.Hardware.ChannelConfigurationType
  langs:
  - csharp
  - vb
  name: AnalogInput
  nameWithType: ChannelConfigurationType.AnalogInput
  fullName: Meadow.Hardware.ChannelConfigurationType.AnalogInput
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: AnalogInput
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
    startLine: 95
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: AnalogInput = 4
    return:
      type: Meadow.Hardware.ChannelConfigurationType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Meadow.Hardware.ChannelConfigurationType.PWM
  commentId: F:Meadow.Hardware.ChannelConfigurationType.PWM
  id: PWM
  parent: Meadow.Hardware.ChannelConfigurationType
  langs:
  - csharp
  - vb
  name: PWM
  nameWithType: ChannelConfigurationType.PWM
  fullName: Meadow.Hardware.ChannelConfigurationType.PWM
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: PWM
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
    startLine: 96
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: PWM = 5
    return:
      type: Meadow.Hardware.ChannelConfigurationType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Meadow.Hardware.ChannelConfigurationType.SPI
  commentId: F:Meadow.Hardware.ChannelConfigurationType.SPI
  id: SPI
  parent: Meadow.Hardware.ChannelConfigurationType
  langs:
  - csharp
  - vb
  name: SPI
  nameWithType: ChannelConfigurationType.SPI
  fullName: Meadow.Hardware.ChannelConfigurationType.SPI
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: SPI
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
    startLine: 97
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: SPI = 6
    return:
      type: Meadow.Hardware.ChannelConfigurationType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Meadow.Hardware.ChannelConfigurationType.I2C
  commentId: F:Meadow.Hardware.ChannelConfigurationType.I2C
  id: I2C
  parent: Meadow.Hardware.ChannelConfigurationType
  langs:
  - csharp
  - vb
  name: I2C
  nameWithType: ChannelConfigurationType.I2C
  fullName: Meadow.Hardware.ChannelConfigurationType.I2C
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: I2C
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
    startLine: 98
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: I2C = 7
    return:
      type: Meadow.Hardware.ChannelConfigurationType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Meadow.Hardware.ChannelConfigurationType.CAN
  commentId: F:Meadow.Hardware.ChannelConfigurationType.CAN
  id: CAN
  parent: Meadow.Hardware.ChannelConfigurationType
  langs:
  - csharp
  - vb
  name: CAN
  nameWithType: ChannelConfigurationType.CAN
  fullName: Meadow.Hardware.ChannelConfigurationType.CAN
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: CAN
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
    startLine: 99
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: CAN = 8
    return:
      type: Meadow.Hardware.ChannelConfigurationType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Meadow.Hardware.ChannelConfigurationType.UART
  commentId: F:Meadow.Hardware.ChannelConfigurationType.UART
  id: UART
  parent: Meadow.Hardware.ChannelConfigurationType
  langs:
  - csharp
  - vb
  name: UART
  nameWithType: ChannelConfigurationType.UART
  fullName: Meadow.Hardware.ChannelConfigurationType.UART
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: UART
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Internals/DeviceChannelManager.cs
    startLine: 100
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: UART = 9
    return:
      type: Meadow.Hardware.ChannelConfigurationType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Meadow.Hardware
  commentId: N:Meadow.Hardware
  name: Meadow.Hardware
  nameWithType: Meadow.Hardware
  fullName: Meadow.Hardware
- uid: Meadow.Hardware.ChannelConfigurationType
  commentId: T:Meadow.Hardware.ChannelConfigurationType
  parent: Meadow.Hardware
  name: ChannelConfigurationType
  nameWithType: ChannelConfigurationType
  fullName: Meadow.Hardware.ChannelConfigurationType
