### YamlMime:ManagedReference
items:
- uid: Meadow.Hardware.Spi.Configuration
  commentId: T:Meadow.Hardware.Spi.Configuration
  id: Spi.Configuration
  parent: Meadow.Hardware
  children:
  - Meadow.Hardware.Spi.Configuration.#ctor(Meadow.Hardware.IDigitalPin,System.Boolean,System.UInt32,System.UInt32,System.Boolean,System.Boolean,System.UInt32,Meadow.Hardware.Spi.SPI_module)
  - Meadow.Hardware.Spi.Configuration.#ctor(Meadow.Hardware.IDigitalPin,System.Boolean,System.UInt32,System.UInt32,System.Boolean,System.Boolean,System.UInt32,Meadow.Hardware.Spi.SPI_module,Meadow.Hardware.IDigitalPin,System.Boolean)
  - Meadow.Hardware.Spi.Configuration.BusyPin
  - Meadow.Hardware.Spi.Configuration.BusyPin_ActiveState
  - Meadow.Hardware.Spi.Configuration.ChipSelect_ActiveState
  - Meadow.Hardware.Spi.Configuration.ChipSelect_HoldTime
  - Meadow.Hardware.Spi.Configuration.ChipSelect_Port
  - Meadow.Hardware.Spi.Configuration.ChipSelect_SetupTime
  - Meadow.Hardware.Spi.Configuration.Clock_Edge
  - Meadow.Hardware.Spi.Configuration.Clock_IdleState
  - Meadow.Hardware.Spi.Configuration.Clock_RateKHz
  - Meadow.Hardware.Spi.Configuration.SPI_mod
  langs:
  - csharp
  - vb
  name: Spi.Configuration
  nameWithType: Spi.Configuration
  fullName: Meadow.Hardware.Spi.Configuration
  type: Class
  source:
    remote:
      path: source/Meadow.Core/Hardware/Spi.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: Configuration
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Spi.cs
    startLine: 36
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: 'public class Configuration : object'
    content.vb: >-
      Public Class Configuration

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Meadow.Hardware.Spi.Configuration.BusyPin
  commentId: F:Meadow.Hardware.Spi.Configuration.BusyPin
  id: BusyPin
  parent: Meadow.Hardware.Spi.Configuration
  langs:
  - csharp
  - vb
  name: BusyPin
  nameWithType: Spi.Configuration.BusyPin
  fullName: Meadow.Hardware.Spi.Configuration.BusyPin
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Spi.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: BusyPin
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Spi.cs
    startLine: 38
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: public readonly IDigitalPin BusyPin
    return:
      type: Meadow.Hardware.IDigitalPin
    content.vb: Public ReadOnly BusyPin As IDigitalPin
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Meadow.Hardware.Spi.Configuration.BusyPin_ActiveState
  commentId: F:Meadow.Hardware.Spi.Configuration.BusyPin_ActiveState
  id: BusyPin_ActiveState
  parent: Meadow.Hardware.Spi.Configuration
  langs:
  - csharp
  - vb
  name: BusyPin_ActiveState
  nameWithType: Spi.Configuration.BusyPin_ActiveState
  fullName: Meadow.Hardware.Spi.Configuration.BusyPin_ActiveState
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Spi.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: BusyPin_ActiveState
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Spi.cs
    startLine: 39
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: public readonly bool BusyPin_ActiveState
    return:
      type: System.Boolean
    content.vb: Public ReadOnly BusyPin_ActiveState As Boolean
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Meadow.Hardware.Spi.Configuration.ChipSelect_ActiveState
  commentId: F:Meadow.Hardware.Spi.Configuration.ChipSelect_ActiveState
  id: ChipSelect_ActiveState
  parent: Meadow.Hardware.Spi.Configuration
  langs:
  - csharp
  - vb
  name: ChipSelect_ActiveState
  nameWithType: Spi.Configuration.ChipSelect_ActiveState
  fullName: Meadow.Hardware.Spi.Configuration.ChipSelect_ActiveState
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Spi.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: ChipSelect_ActiveState
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Spi.cs
    startLine: 40
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: public readonly bool ChipSelect_ActiveState
    return:
      type: System.Boolean
    content.vb: Public ReadOnly ChipSelect_ActiveState As Boolean
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Meadow.Hardware.Spi.Configuration.ChipSelect_HoldTime
  commentId: F:Meadow.Hardware.Spi.Configuration.ChipSelect_HoldTime
  id: ChipSelect_HoldTime
  parent: Meadow.Hardware.Spi.Configuration
  langs:
  - csharp
  - vb
  name: ChipSelect_HoldTime
  nameWithType: Spi.Configuration.ChipSelect_HoldTime
  fullName: Meadow.Hardware.Spi.Configuration.ChipSelect_HoldTime
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Spi.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: ChipSelect_HoldTime
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Spi.cs
    startLine: 41
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: public readonly uint ChipSelect_HoldTime
    return:
      type: System.UInt32
    content.vb: Public ReadOnly ChipSelect_HoldTime As UInteger
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Meadow.Hardware.Spi.Configuration.ChipSelect_Port
  commentId: F:Meadow.Hardware.Spi.Configuration.ChipSelect_Port
  id: ChipSelect_Port
  parent: Meadow.Hardware.Spi.Configuration
  langs:
  - csharp
  - vb
  name: ChipSelect_Port
  nameWithType: Spi.Configuration.ChipSelect_Port
  fullName: Meadow.Hardware.Spi.Configuration.ChipSelect_Port
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Spi.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: ChipSelect_Port
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Spi.cs
    startLine: 42
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: public readonly IDigitalPin ChipSelect_Port
    return:
      type: Meadow.Hardware.IDigitalPin
    content.vb: Public ReadOnly ChipSelect_Port As IDigitalPin
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Meadow.Hardware.Spi.Configuration.ChipSelect_SetupTime
  commentId: F:Meadow.Hardware.Spi.Configuration.ChipSelect_SetupTime
  id: ChipSelect_SetupTime
  parent: Meadow.Hardware.Spi.Configuration
  langs:
  - csharp
  - vb
  name: ChipSelect_SetupTime
  nameWithType: Spi.Configuration.ChipSelect_SetupTime
  fullName: Meadow.Hardware.Spi.Configuration.ChipSelect_SetupTime
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Spi.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: ChipSelect_SetupTime
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Spi.cs
    startLine: 43
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: public readonly uint ChipSelect_SetupTime
    return:
      type: System.UInt32
    content.vb: Public ReadOnly ChipSelect_SetupTime As UInteger
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Meadow.Hardware.Spi.Configuration.Clock_Edge
  commentId: F:Meadow.Hardware.Spi.Configuration.Clock_Edge
  id: Clock_Edge
  parent: Meadow.Hardware.Spi.Configuration
  langs:
  - csharp
  - vb
  name: Clock_Edge
  nameWithType: Spi.Configuration.Clock_Edge
  fullName: Meadow.Hardware.Spi.Configuration.Clock_Edge
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Spi.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: Clock_Edge
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Spi.cs
    startLine: 44
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: public readonly bool Clock_Edge
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Clock_Edge As Boolean
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Meadow.Hardware.Spi.Configuration.Clock_IdleState
  commentId: F:Meadow.Hardware.Spi.Configuration.Clock_IdleState
  id: Clock_IdleState
  parent: Meadow.Hardware.Spi.Configuration
  langs:
  - csharp
  - vb
  name: Clock_IdleState
  nameWithType: Spi.Configuration.Clock_IdleState
  fullName: Meadow.Hardware.Spi.Configuration.Clock_IdleState
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Spi.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: Clock_IdleState
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Spi.cs
    startLine: 45
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: public readonly bool Clock_IdleState
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Clock_IdleState As Boolean
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Meadow.Hardware.Spi.Configuration.Clock_RateKHz
  commentId: F:Meadow.Hardware.Spi.Configuration.Clock_RateKHz
  id: Clock_RateKHz
  parent: Meadow.Hardware.Spi.Configuration
  langs:
  - csharp
  - vb
  name: Clock_RateKHz
  nameWithType: Spi.Configuration.Clock_RateKHz
  fullName: Meadow.Hardware.Spi.Configuration.Clock_RateKHz
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Spi.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: Clock_RateKHz
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Spi.cs
    startLine: 46
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: public readonly uint Clock_RateKHz
    return:
      type: System.UInt32
    content.vb: Public ReadOnly Clock_RateKHz As UInteger
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Meadow.Hardware.Spi.Configuration.SPI_mod
  commentId: F:Meadow.Hardware.Spi.Configuration.SPI_mod
  id: SPI_mod
  parent: Meadow.Hardware.Spi.Configuration
  langs:
  - csharp
  - vb
  name: SPI_mod
  nameWithType: Spi.Configuration.SPI_mod
  fullName: Meadow.Hardware.Spi.Configuration.SPI_mod
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Spi.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: SPI_mod
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Spi.cs
    startLine: 47
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: public readonly Spi.SPI_module SPI_mod
    return:
      type: Meadow.Hardware.Spi.SPI_module
    content.vb: Public ReadOnly SPI_mod As Spi.SPI_module
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Meadow.Hardware.Spi.Configuration.#ctor(Meadow.Hardware.IDigitalPin,System.Boolean,System.UInt32,System.UInt32,System.Boolean,System.Boolean,System.UInt32,Meadow.Hardware.Spi.SPI_module)
  commentId: M:Meadow.Hardware.Spi.Configuration.#ctor(Meadow.Hardware.IDigitalPin,System.Boolean,System.UInt32,System.UInt32,System.Boolean,System.Boolean,System.UInt32,Meadow.Hardware.Spi.SPI_module)
  id: '#ctor(Meadow.Hardware.IDigitalPin,System.Boolean,System.UInt32,System.UInt32,System.Boolean,System.Boolean,System.UInt32,Meadow.Hardware.Spi.SPI_module)'
  parent: Meadow.Hardware.Spi.Configuration
  langs:
  - csharp
  - vb
  name: Configuration(IDigitalPin, Boolean, UInt32, UInt32, Boolean, Boolean, UInt32, Spi.SPI_module)
  nameWithType: Spi.Configuration.Configuration(IDigitalPin, Boolean, UInt32, UInt32, Boolean, Boolean, UInt32, Spi.SPI_module)
  fullName: Meadow.Hardware.Spi.Configuration.Configuration(Meadow.Hardware.IDigitalPin, System.Boolean, System.UInt32, System.UInt32, System.Boolean, System.Boolean, System.UInt32, Meadow.Hardware.Spi.SPI_module)
  type: Constructor
  source:
    remote:
      path: source/Meadow.Core/Hardware/Spi.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: .ctor
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Spi.cs
    startLine: 49
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: public Configuration(IDigitalPin ChipSelect_Port, bool ChipSelect_ActiveState, uint ChipSelect_SetupTime, uint ChipSelect_HoldTime, bool Clock_IdleState, bool Clock_Edge, uint Clock_RateKHz, Spi.SPI_module SPI_mod)
    parameters:
    - id: ChipSelect_Port
      type: Meadow.Hardware.IDigitalPin
    - id: ChipSelect_ActiveState
      type: System.Boolean
    - id: ChipSelect_SetupTime
      type: System.UInt32
    - id: ChipSelect_HoldTime
      type: System.UInt32
    - id: Clock_IdleState
      type: System.Boolean
    - id: Clock_Edge
      type: System.Boolean
    - id: Clock_RateKHz
      type: System.UInt32
    - id: SPI_mod
      type: Meadow.Hardware.Spi.SPI_module
    content.vb: Public Sub New(ChipSelect_Port As IDigitalPin, ChipSelect_ActiveState As Boolean, ChipSelect_SetupTime As UInteger, ChipSelect_HoldTime As UInteger, Clock_IdleState As Boolean, Clock_Edge As Boolean, Clock_RateKHz As UInteger, SPI_mod As Spi.SPI_module)
  overload: Meadow.Hardware.Spi.Configuration.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Meadow.Hardware.Spi.Configuration.#ctor(Meadow.Hardware.IDigitalPin,System.Boolean,System.UInt32,System.UInt32,System.Boolean,System.Boolean,System.UInt32,Meadow.Hardware.Spi.SPI_module,Meadow.Hardware.IDigitalPin,System.Boolean)
  commentId: M:Meadow.Hardware.Spi.Configuration.#ctor(Meadow.Hardware.IDigitalPin,System.Boolean,System.UInt32,System.UInt32,System.Boolean,System.Boolean,System.UInt32,Meadow.Hardware.Spi.SPI_module,Meadow.Hardware.IDigitalPin,System.Boolean)
  id: '#ctor(Meadow.Hardware.IDigitalPin,System.Boolean,System.UInt32,System.UInt32,System.Boolean,System.Boolean,System.UInt32,Meadow.Hardware.Spi.SPI_module,Meadow.Hardware.IDigitalPin,System.Boolean)'
  parent: Meadow.Hardware.Spi.Configuration
  langs:
  - csharp
  - vb
  name: Configuration(IDigitalPin, Boolean, UInt32, UInt32, Boolean, Boolean, UInt32, Spi.SPI_module, IDigitalPin, Boolean)
  nameWithType: Spi.Configuration.Configuration(IDigitalPin, Boolean, UInt32, UInt32, Boolean, Boolean, UInt32, Spi.SPI_module, IDigitalPin, Boolean)
  fullName: Meadow.Hardware.Spi.Configuration.Configuration(Meadow.Hardware.IDigitalPin, System.Boolean, System.UInt32, System.UInt32, System.Boolean, System.Boolean, System.UInt32, Meadow.Hardware.Spi.SPI_module, Meadow.Hardware.IDigitalPin, System.Boolean)
  type: Constructor
  source:
    remote:
      path: source/Meadow.Core/Hardware/Spi.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: .ctor
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Spi.cs
    startLine: 51
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: public Configuration(IDigitalPin ChipSelect_Port, bool ChipSelect_ActiveState, uint ChipSelect_SetupTime, uint ChipSelect_HoldTime, bool Clock_IdleState, bool Clock_Edge, uint Clock_RateKHz, Spi.SPI_module SPI_mod, IDigitalPin BusyPin, bool BusyPin_ActiveState)
    parameters:
    - id: ChipSelect_Port
      type: Meadow.Hardware.IDigitalPin
    - id: ChipSelect_ActiveState
      type: System.Boolean
    - id: ChipSelect_SetupTime
      type: System.UInt32
    - id: ChipSelect_HoldTime
      type: System.UInt32
    - id: Clock_IdleState
      type: System.Boolean
    - id: Clock_Edge
      type: System.Boolean
    - id: Clock_RateKHz
      type: System.UInt32
    - id: SPI_mod
      type: Meadow.Hardware.Spi.SPI_module
    - id: BusyPin
      type: Meadow.Hardware.IDigitalPin
    - id: BusyPin_ActiveState
      type: System.Boolean
    content.vb: Public Sub New(ChipSelect_Port As IDigitalPin, ChipSelect_ActiveState As Boolean, ChipSelect_SetupTime As UInteger, ChipSelect_HoldTime As UInteger, Clock_IdleState As Boolean, Clock_Edge As Boolean, Clock_RateKHz As UInteger, SPI_mod As Spi.SPI_module, BusyPin As IDigitalPin, BusyPin_ActiveState As Boolean)
  overload: Meadow.Hardware.Spi.Configuration.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Meadow.Hardware
  commentId: N:Meadow.Hardware
  name: Meadow.Hardware
  nameWithType: Meadow.Hardware
  fullName: Meadow.Hardware
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Meadow.Hardware.IDigitalPin
  commentId: T:Meadow.Hardware.IDigitalPin
  parent: Meadow.Hardware
  name: IDigitalPin
  nameWithType: IDigitalPin
  fullName: Meadow.Hardware.IDigitalPin
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.UInt32
  isExternal: true
  name: UInt32
  nameWithType: UInt32
  fullName: System.UInt32
- uid: Meadow.Hardware.Spi.SPI_module
  commentId: T:Meadow.Hardware.Spi.SPI_module
  parent: Meadow.Hardware
  name: Spi.SPI_module
  nameWithType: Spi.SPI_module
  fullName: Meadow.Hardware.Spi.SPI_module
- uid: Meadow.Hardware.Spi.Configuration.#ctor*
  commentId: Overload:Meadow.Hardware.Spi.Configuration.#ctor
  name: Configuration
  nameWithType: Spi.Configuration.Configuration
  fullName: Meadow.Hardware.Spi.Configuration.Configuration
