### YamlMime:ManagedReference
items:
- uid: Meadow.Hardware.I2cDevice.Configuration
  commentId: T:Meadow.Hardware.I2cDevice.Configuration
  id: I2cDevice.Configuration
  parent: Meadow.Hardware
  children:
  - Meadow.Hardware.I2cDevice.Configuration.#ctor(System.UInt16,System.Int32)
  - Meadow.Hardware.I2cDevice.Configuration.Address
  - Meadow.Hardware.I2cDevice.Configuration.ClockRateKhz
  langs:
  - csharp
  - vb
  name: I2cDevice.Configuration
  nameWithType: I2cDevice.Configuration
  fullName: Meadow.Hardware.I2cDevice.Configuration
  type: Class
  source:
    remote:
      path: source/Meadow.Core/Hardware/Contracts/I2cDevice.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: Configuration
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Contracts/I2cDevice.cs
    startLine: 18
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: 'public class Configuration : object'
    content.vb: >-
      Public Class Configuration

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Meadow.Hardware.I2cDevice.Configuration.Address
  commentId: F:Meadow.Hardware.I2cDevice.Configuration.Address
  id: Address
  parent: Meadow.Hardware.I2cDevice.Configuration
  langs:
  - csharp
  - vb
  name: Address
  nameWithType: I2cDevice.Configuration.Address
  fullName: Meadow.Hardware.I2cDevice.Configuration.Address
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Contracts/I2cDevice.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: Address
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Contracts/I2cDevice.cs
    startLine: 20
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: public readonly ushort Address
    return:
      type: System.UInt16
    content.vb: Public ReadOnly Address As UShort
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Meadow.Hardware.I2cDevice.Configuration.ClockRateKhz
  commentId: F:Meadow.Hardware.I2cDevice.Configuration.ClockRateKhz
  id: ClockRateKhz
  parent: Meadow.Hardware.I2cDevice.Configuration
  langs:
  - csharp
  - vb
  name: ClockRateKhz
  nameWithType: I2cDevice.Configuration.ClockRateKhz
  fullName: Meadow.Hardware.I2cDevice.Configuration.ClockRateKhz
  type: Field
  source:
    remote:
      path: source/Meadow.Core/Hardware/Contracts/I2cDevice.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: ClockRateKhz
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Contracts/I2cDevice.cs
    startLine: 21
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: public readonly int ClockRateKhz
    return:
      type: System.Int32
    content.vb: Public ReadOnly ClockRateKhz As Integer
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Meadow.Hardware.I2cDevice.Configuration.#ctor(System.UInt16,System.Int32)
  commentId: M:Meadow.Hardware.I2cDevice.Configuration.#ctor(System.UInt16,System.Int32)
  id: '#ctor(System.UInt16,System.Int32)'
  parent: Meadow.Hardware.I2cDevice.Configuration
  langs:
  - csharp
  - vb
  name: Configuration(UInt16, Int32)
  nameWithType: I2cDevice.Configuration.Configuration(UInt16, Int32)
  fullName: Meadow.Hardware.I2cDevice.Configuration.Configuration(System.UInt16, System.Int32)
  type: Constructor
  source:
    remote:
      path: source/Meadow.Core/Hardware/Contracts/I2cDevice.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: .ctor
    path: ../Meadow.Core/source/Meadow.Core/Hardware/Contracts/I2cDevice.cs
    startLine: 23
  assemblies:
  - Meadow.Core
  namespace: Meadow.Hardware
  syntax:
    content: public Configuration(ushort address, int clockRateKhz)
    parameters:
    - id: address
      type: System.UInt16
    - id: clockRateKhz
      type: System.Int32
    content.vb: Public Sub New(address As UShort, clockRateKhz As Integer)
  overload: Meadow.Hardware.I2cDevice.Configuration.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Meadow.Hardware
  commentId: N:Meadow.Hardware
  name: Meadow.Hardware
  nameWithType: Meadow.Hardware
  fullName: Meadow.Hardware
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.UInt16
  isExternal: true
  name: UInt16
  nameWithType: UInt16
  fullName: System.UInt16
- uid: System.Int32
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Meadow.Hardware.I2cDevice.Configuration.#ctor*
  commentId: Overload:Meadow.Hardware.I2cDevice.Configuration.#ctor
  name: Configuration
  nameWithType: I2cDevice.Configuration.Configuration
  fullName: Meadow.Hardware.I2cDevice.Configuration.Configuration
