### YamlMime:ManagedReference
items:
- uid: MeadowApplication.MyApp
  commentId: T:MeadowApplication.MyApp
  id: MyApp
  parent: MeadowApplication
  children:
  - MeadowApplication.MyApp.#ctor
  - MeadowApplication.MyApp._running
  - MeadowApplication.MyApp.Run
  - MeadowApplication.MyApp.StartDoingSomeStuff
  langs:
  - csharp
  - vb
  name: MyApp
  nameWithType: MyApp
  fullName: MeadowApplication.MyApp
  type: Class
  source:
    remote:
      path: source/Tests/MeadowApplication/MyApp.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: MyApp
    path: ../Meadow.Core/source/Tests/MeadowApplication/MyApp.cs
    startLine: 7
  assemblies:
  - MeadowApplication
  namespace: MeadowApplication
  syntax:
    content: 'public class MyApp : AppBase<F7Micro, MyApp>, IApp'
    content.vb: >-
      Public Class MyApp

          Inherits AppBase(Of F7Micro, MyApp)

          Implements IApp
  inheritance:
  - System.Object
  - Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}
  implements:
  - Meadow.IApp
  inheritedMembers:
  - Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.Current
  - Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.Device
  - Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.Run
  - Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.WillSleep
  - Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.OnWake
  - Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.WillReset
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: MeadowApplication.MyApp._running
  commentId: F:MeadowApplication.MyApp._running
  id: _running
  parent: MeadowApplication.MyApp
  langs:
  - csharp
  - vb
  name: _running
  nameWithType: MyApp._running
  fullName: MeadowApplication.MyApp._running
  type: Field
  source:
    remote:
      path: source/Tests/MeadowApplication/MyApp.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: _running
    path: ../Meadow.Core/source/Tests/MeadowApplication/MyApp.cs
    startLine: 9
  assemblies:
  - MeadowApplication
  namespace: MeadowApplication
  syntax:
    content: protected bool _running
    return:
      type: System.Boolean
    content.vb: Protected _running As Boolean
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
- uid: MeadowApplication.MyApp.#ctor
  commentId: M:MeadowApplication.MyApp.#ctor
  id: '#ctor'
  parent: MeadowApplication.MyApp
  langs:
  - csharp
  - vb
  name: MyApp()
  nameWithType: MyApp.MyApp()
  fullName: MeadowApplication.MyApp.MyApp()
  type: Constructor
  source:
    remote:
      path: source/Tests/MeadowApplication/MyApp.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: .ctor
    path: ../Meadow.Core/source/Tests/MeadowApplication/MyApp.cs
    startLine: 11
  assemblies:
  - MeadowApplication
  namespace: MeadowApplication
  syntax:
    content: public MyApp()
    content.vb: Public Sub New
  overload: MeadowApplication.MyApp.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: MeadowApplication.MyApp.Run
  commentId: M:MeadowApplication.MyApp.Run
  id: Run
  parent: MeadowApplication.MyApp
  langs:
  - csharp
  - vb
  name: Run()
  nameWithType: MyApp.Run()
  fullName: MeadowApplication.MyApp.Run()
  type: Method
  source:
    remote:
      path: source/Tests/MeadowApplication/MyApp.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: Run
    path: ../Meadow.Core/source/Tests/MeadowApplication/MyApp.cs
    startLine: 19
  assemblies:
  - MeadowApplication
  namespace: MeadowApplication
  syntax:
    content: public override void Run()
    content.vb: Public Overrides Sub Run
  overridden: Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.Run
  overload: MeadowApplication.MyApp.Run*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: MeadowApplication.MyApp.StartDoingSomeStuff
  commentId: M:MeadowApplication.MyApp.StartDoingSomeStuff
  id: StartDoingSomeStuff
  parent: MeadowApplication.MyApp
  langs:
  - csharp
  - vb
  name: StartDoingSomeStuff()
  nameWithType: MyApp.StartDoingSomeStuff()
  fullName: MeadowApplication.MyApp.StartDoingSomeStuff()
  type: Method
  source:
    remote:
      path: source/Tests/MeadowApplication/MyApp.cs
      branch: master
      repo: https://github.com/WildernessLabs/Meadow.Core.git
    id: StartDoingSomeStuff
    path: ../Meadow.Core/source/Tests/MeadowApplication/MyApp.cs
    startLine: 24
  assemblies:
  - MeadowApplication
  namespace: MeadowApplication
  syntax:
    content: public void StartDoingSomeStuff()
    content.vb: Public Sub StartDoingSomeStuff
  overload: MeadowApplication.MyApp.StartDoingSomeStuff*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: MeadowApplication
  commentId: N:MeadowApplication
  name: MeadowApplication
  nameWithType: MeadowApplication
  fullName: MeadowApplication
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}
  commentId: T:Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}
  parent: Meadow
  definition: Meadow.AppBase`2
  name: AppBase<F7Micro, MyApp>
  nameWithType: AppBase<F7Micro, MyApp>
  fullName: Meadow.AppBase<Meadow.Devices.F7Micro, MeadowApplication.MyApp>
  nameWithType.vb: AppBase(Of F7Micro, MyApp)
  fullName.vb: Meadow.AppBase(Of Meadow.Devices.F7Micro, MeadowApplication.MyApp)
  name.vb: AppBase(Of F7Micro, MyApp)
  spec.csharp:
  - uid: Meadow.AppBase`2
    name: AppBase
    nameWithType: AppBase
    fullName: Meadow.AppBase
  - name: <
    nameWithType: <
    fullName: <
  - uid: Meadow.Devices.F7Micro
    name: F7Micro
    nameWithType: F7Micro
    fullName: Meadow.Devices.F7Micro
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: MeadowApplication.MyApp
    name: MyApp
    nameWithType: MyApp
    fullName: MeadowApplication.MyApp
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Meadow.AppBase`2
    name: AppBase
    nameWithType: AppBase
    fullName: Meadow.AppBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Meadow.Devices.F7Micro
    name: F7Micro
    nameWithType: F7Micro
    fullName: Meadow.Devices.F7Micro
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: MeadowApplication.MyApp
    name: MyApp
    nameWithType: MyApp
    fullName: MeadowApplication.MyApp
  - name: )
    nameWithType: )
    fullName: )
- uid: Meadow.IApp
  commentId: T:Meadow.IApp
  parent: Meadow
  name: IApp
  nameWithType: IApp
  fullName: Meadow.IApp
- uid: Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.Current
  commentId: P:Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.Current
  parent: Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}
  definition: Meadow.AppBase`2.Current
  name: Current
  nameWithType: AppBase<F7Micro, MyApp>.Current
  fullName: Meadow.AppBase<Meadow.Devices.F7Micro, MeadowApplication.MyApp>.Current
  nameWithType.vb: AppBase(Of F7Micro, MyApp).Current
  fullName.vb: Meadow.AppBase(Of Meadow.Devices.F7Micro, MeadowApplication.MyApp).Current
- uid: Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.Device
  commentId: P:Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.Device
  parent: Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}
  definition: Meadow.AppBase`2.Device
  name: Device
  nameWithType: AppBase<F7Micro, MyApp>.Device
  fullName: Meadow.AppBase<Meadow.Devices.F7Micro, MeadowApplication.MyApp>.Device
  nameWithType.vb: AppBase(Of F7Micro, MyApp).Device
  fullName.vb: Meadow.AppBase(Of Meadow.Devices.F7Micro, MeadowApplication.MyApp).Device
- uid: Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.Run
  commentId: M:Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.Run
  parent: Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}
  definition: Meadow.AppBase`2.Run
  name: Run()
  nameWithType: AppBase<F7Micro, MyApp>.Run()
  fullName: Meadow.AppBase<Meadow.Devices.F7Micro, MeadowApplication.MyApp>.Run()
  nameWithType.vb: AppBase(Of F7Micro, MyApp).Run()
  fullName.vb: Meadow.AppBase(Of Meadow.Devices.F7Micro, MeadowApplication.MyApp).Run()
  spec.csharp:
  - uid: Meadow.AppBase`2.Run
    name: Run
    nameWithType: AppBase<F7Micro, MyApp>.Run
    fullName: Meadow.AppBase<Meadow.Devices.F7Micro, MeadowApplication.MyApp>.Run
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Meadow.AppBase`2.Run
    name: Run
    nameWithType: AppBase(Of F7Micro, MyApp).Run
    fullName: Meadow.AppBase(Of Meadow.Devices.F7Micro, MeadowApplication.MyApp).Run
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.WillSleep
  commentId: M:Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.WillSleep
  parent: Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}
  definition: Meadow.AppBase`2.WillSleep
  name: WillSleep()
  nameWithType: AppBase<F7Micro, MyApp>.WillSleep()
  fullName: Meadow.AppBase<Meadow.Devices.F7Micro, MeadowApplication.MyApp>.WillSleep()
  nameWithType.vb: AppBase(Of F7Micro, MyApp).WillSleep()
  fullName.vb: Meadow.AppBase(Of Meadow.Devices.F7Micro, MeadowApplication.MyApp).WillSleep()
  spec.csharp:
  - uid: Meadow.AppBase`2.WillSleep
    name: WillSleep
    nameWithType: AppBase<F7Micro, MyApp>.WillSleep
    fullName: Meadow.AppBase<Meadow.Devices.F7Micro, MeadowApplication.MyApp>.WillSleep
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Meadow.AppBase`2.WillSleep
    name: WillSleep
    nameWithType: AppBase(Of F7Micro, MyApp).WillSleep
    fullName: Meadow.AppBase(Of Meadow.Devices.F7Micro, MeadowApplication.MyApp).WillSleep
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.OnWake
  commentId: M:Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.OnWake
  parent: Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}
  definition: Meadow.AppBase`2.OnWake
  name: OnWake()
  nameWithType: AppBase<F7Micro, MyApp>.OnWake()
  fullName: Meadow.AppBase<Meadow.Devices.F7Micro, MeadowApplication.MyApp>.OnWake()
  nameWithType.vb: AppBase(Of F7Micro, MyApp).OnWake()
  fullName.vb: Meadow.AppBase(Of Meadow.Devices.F7Micro, MeadowApplication.MyApp).OnWake()
  spec.csharp:
  - uid: Meadow.AppBase`2.OnWake
    name: OnWake
    nameWithType: AppBase<F7Micro, MyApp>.OnWake
    fullName: Meadow.AppBase<Meadow.Devices.F7Micro, MeadowApplication.MyApp>.OnWake
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Meadow.AppBase`2.OnWake
    name: OnWake
    nameWithType: AppBase(Of F7Micro, MyApp).OnWake
    fullName: Meadow.AppBase(Of Meadow.Devices.F7Micro, MeadowApplication.MyApp).OnWake
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.WillReset
  commentId: M:Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}.WillReset
  parent: Meadow.AppBase{Meadow.Devices.F7Micro,MeadowApplication.MyApp}
  definition: Meadow.AppBase`2.WillReset
  name: WillReset()
  nameWithType: AppBase<F7Micro, MyApp>.WillReset()
  fullName: Meadow.AppBase<Meadow.Devices.F7Micro, MeadowApplication.MyApp>.WillReset()
  nameWithType.vb: AppBase(Of F7Micro, MyApp).WillReset()
  fullName.vb: Meadow.AppBase(Of Meadow.Devices.F7Micro, MeadowApplication.MyApp).WillReset()
  spec.csharp:
  - uid: Meadow.AppBase`2.WillReset
    name: WillReset
    nameWithType: AppBase<F7Micro, MyApp>.WillReset
    fullName: Meadow.AppBase<Meadow.Devices.F7Micro, MeadowApplication.MyApp>.WillReset
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Meadow.AppBase`2.WillReset
    name: WillReset
    nameWithType: AppBase(Of F7Micro, MyApp).WillReset
    fullName: Meadow.AppBase(Of Meadow.Devices.F7Micro, MeadowApplication.MyApp).WillReset
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Meadow.AppBase`2
  commentId: T:Meadow.AppBase`2
  name: AppBase<D, A>
  nameWithType: AppBase<D, A>
  fullName: Meadow.AppBase<D, A>
  nameWithType.vb: AppBase(Of D, A)
  fullName.vb: Meadow.AppBase(Of D, A)
  name.vb: AppBase(Of D, A)
  spec.csharp:
  - uid: Meadow.AppBase`2
    name: AppBase
    nameWithType: AppBase
    fullName: Meadow.AppBase
  - name: <
    nameWithType: <
    fullName: <
  - name: D
    nameWithType: D
    fullName: D
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: A
    nameWithType: A
    fullName: A
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Meadow.AppBase`2
    name: AppBase
    nameWithType: AppBase
    fullName: Meadow.AppBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: D
    nameWithType: D
    fullName: D
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: A
    nameWithType: A
    fullName: A
  - name: )
    nameWithType: )
    fullName: )
- uid: Meadow
  commentId: N:Meadow
  name: Meadow
  nameWithType: Meadow
  fullName: Meadow
- uid: Meadow.AppBase`2.Current
  commentId: P:Meadow.AppBase`2.Current
  name: Current
  nameWithType: AppBase<D, A>.Current
  fullName: Meadow.AppBase<D, A>.Current
  nameWithType.vb: AppBase(Of D, A).Current
  fullName.vb: Meadow.AppBase(Of D, A).Current
- uid: Meadow.AppBase`2.Device
  commentId: P:Meadow.AppBase`2.Device
  name: Device
  nameWithType: AppBase<D, A>.Device
  fullName: Meadow.AppBase<D, A>.Device
  nameWithType.vb: AppBase(Of D, A).Device
  fullName.vb: Meadow.AppBase(Of D, A).Device
- uid: Meadow.AppBase`2.Run
  commentId: M:Meadow.AppBase`2.Run
  name: Run()
  nameWithType: AppBase<D, A>.Run()
  fullName: Meadow.AppBase<D, A>.Run()
  nameWithType.vb: AppBase(Of D, A).Run()
  fullName.vb: Meadow.AppBase(Of D, A).Run()
  spec.csharp:
  - uid: Meadow.AppBase`2.Run
    name: Run
    nameWithType: AppBase<D, A>.Run
    fullName: Meadow.AppBase<D, A>.Run
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Meadow.AppBase`2.Run
    name: Run
    nameWithType: AppBase(Of D, A).Run
    fullName: Meadow.AppBase(Of D, A).Run
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Meadow.AppBase`2.WillSleep
  commentId: M:Meadow.AppBase`2.WillSleep
  name: WillSleep()
  nameWithType: AppBase<D, A>.WillSleep()
  fullName: Meadow.AppBase<D, A>.WillSleep()
  nameWithType.vb: AppBase(Of D, A).WillSleep()
  fullName.vb: Meadow.AppBase(Of D, A).WillSleep()
  spec.csharp:
  - uid: Meadow.AppBase`2.WillSleep
    name: WillSleep
    nameWithType: AppBase<D, A>.WillSleep
    fullName: Meadow.AppBase<D, A>.WillSleep
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Meadow.AppBase`2.WillSleep
    name: WillSleep
    nameWithType: AppBase(Of D, A).WillSleep
    fullName: Meadow.AppBase(Of D, A).WillSleep
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Meadow.AppBase`2.OnWake
  commentId: M:Meadow.AppBase`2.OnWake
  name: OnWake()
  nameWithType: AppBase<D, A>.OnWake()
  fullName: Meadow.AppBase<D, A>.OnWake()
  nameWithType.vb: AppBase(Of D, A).OnWake()
  fullName.vb: Meadow.AppBase(Of D, A).OnWake()
  spec.csharp:
  - uid: Meadow.AppBase`2.OnWake
    name: OnWake
    nameWithType: AppBase<D, A>.OnWake
    fullName: Meadow.AppBase<D, A>.OnWake
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Meadow.AppBase`2.OnWake
    name: OnWake
    nameWithType: AppBase(Of D, A).OnWake
    fullName: Meadow.AppBase(Of D, A).OnWake
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Meadow.AppBase`2.WillReset
  commentId: M:Meadow.AppBase`2.WillReset
  name: WillReset()
  nameWithType: AppBase<D, A>.WillReset()
  fullName: Meadow.AppBase<D, A>.WillReset()
  nameWithType.vb: AppBase(Of D, A).WillReset()
  fullName.vb: Meadow.AppBase(Of D, A).WillReset()
  spec.csharp:
  - uid: Meadow.AppBase`2.WillReset
    name: WillReset
    nameWithType: AppBase<D, A>.WillReset
    fullName: Meadow.AppBase<D, A>.WillReset
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Meadow.AppBase`2.WillReset
    name: WillReset
    nameWithType: AppBase(Of D, A).WillReset
    fullName: Meadow.AppBase(Of D, A).WillReset
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: MeadowApplication.MyApp.#ctor*
  commentId: Overload:MeadowApplication.MyApp.#ctor
  name: MyApp
  nameWithType: MyApp.MyApp
  fullName: MeadowApplication.MyApp.MyApp
- uid: MeadowApplication.MyApp.Run*
  commentId: Overload:MeadowApplication.MyApp.Run
  name: Run
  nameWithType: MyApp.Run
  fullName: MeadowApplication.MyApp.Run
- uid: MeadowApplication.MyApp.StartDoingSomeStuff*
  commentId: Overload:MeadowApplication.MyApp.StartDoingSomeStuff
  name: StartDoingSomeStuff
  nameWithType: MyApp.StartDoingSomeStuff
  fullName: MeadowApplication.MyApp.StartDoingSomeStuff
